document.addEventListener('DOMContentLoaded', function() {
    const birthdays = [
        { name: 'Aryan Chandrakant Giri', birthday: '23-03' },
        { name: 'Bhavin Vipul Chopada', birthday: '08-01' },
        { name: 'Divika Vijay Verma', birthday: '03-04' },
        { name: 'H Srivanth', birthday: '09-03' },
        { name: 'Hridamee Sunit Mhasade', birthday: '02-11' },
        { name: 'Jay Umesh Tajanpure', birthday: '17-11' },
        { name: 'Meher Umesh Agarwal', birthday: '19-08' },
        { name: 'Nitiksha Roshan Chavan', birthday: '27-01' },
        { name: 'Prasanna Madhukar Dhage', birthday: '04-07' },
        { name: 'Reyansh Chinmay Tambat', birthday: '14-06' },
        { name: 'Roshita Rohit Jain', birthday: '06-10' },
        { name: 'Samarth Chandrakant Yadav', birthday: '04-04' },
        { name: 'Sanjita Anil Jagtap', birthday: '18-12' },
        { name: 'Sehrhan Mansuri', birthday: '11-07' },
        { name: 'Shivam Vijay Arambhi', birthday: '07-03' },
        { name: 'Smira Suchit Patni', birthday: '30-04' },
        { name: 'Suhani Sonali Pagare', birthday: '22-12' },
        { name: 'Swara Sudarshan Suryawanshi', birthday: '04-06' },
        { name: 'Tanmay Anil Bute', birthday: '07-10' },
        { name: 'Tanvi Bhaskar Gawali', birthday: '12-09' },
        { name: 'Tisha Gaurav Chordiya', birthday: '05-01' },
        { name: 'Vedika Harivansh Prajapati', birthday: '12-10' },
        { name: 'Vihan Kailas Ashtekar', birthday: '21-05' },
        { name: 'Vivaan Ravi Kumar', birthday: '11-11' },
        { name: 'Aaditya Pradip Shelake', birthday: '01-11' },
        { name: 'Abhinav Roy', birthday: '19-08' },
        { name: 'Adhira Ganesh Shinde', birthday: '06-07' },
        { name: 'Aditi Rajesh Borse', birthday: '23-01' },
        { name: 'Aditi Tushar Mhaske', birthday: '21-11' },
        { name: 'Anjani Dilip Kapse', birthday: '18-04' },
        { name: 'Ansh Ahire', birthday: '22-06' },
        { name: 'Archit Chaitanya Kumbharde', birthday: '19-08' },
        { name: 'Athaansh Amit Kantikar', birthday: '26-11' },
        { name: 'Avika Amit Chordiya', birthday: '20-02' },
        { name: 'Bilquis Mufaddal Nawab', birthday: '03-03' },
        { name: 'Devansh Yogesh Patil', birthday: '11-02' },
        { name: 'Eshaan Sharma', birthday: '23-09' },
        { name: 'Jaisvi Manish Bajaj', birthday: '29-03' },
        { name: 'Kundan Sandeep Pekhale', birthday: '14-02' },
        { name: 'Lidwina Jami', birthday: '18-01' },
        { name: 'Maitreyee Sujit Nevase', birthday: '28-10' },
        { name: 'Meet Harshal Badgujar', birthday: '09-10' },
        { name: 'Mishika Sarkar', birthday: '30-12' },
        { name: 'Naisha Shrivastava', birthday: '07-03' },
        { name: 'Ojasvi Ajit Kushare', birthday: '22-08' },
        { name: 'Ridhaan Pankaj Yeole', birthday: '22-07' },
        { name: 'Ridhit Parijeet Ghike', birthday: '17-05' },
        { name: 'Sachi Prasad Yeole', birthday: '23-09' },
        { name: 'Samarth Baghel', birthday: '19-01' },
        { name: 'Shanaya Pravin Sanap', birthday: '09-05' },
        { name: 'Shivaanya Sangamesh Kupast', birthday: '14-02' },
        { name: 'Shivaksh Yogesh Aher', birthday: '24-12' },
        { name: 'Shivansh Amit Sonawane', birthday: '08-11' },
        { name: 'Shivnya Sagar Khode', birthday: '16-07' },
        { name: 'Shivtej Darshan Talikot', birthday: '19-02' },
        { name: 'Shreejay Vijay Tile', birthday: '23-05' },
        { name: 'Swara Vijay Nagare', birthday: '17-12' },
        { name: 'Swayam Siddharth Bhogle', birthday: '12-12' },
        { name: 'Aadya Jha', birthday: '31-03' },
        { name: 'Aayra Virendra Lawande', birthday: '10-12' },
        { name: 'Advira Vinayak Bachhav', birthday: '29-10' },
        { name: 'Arjun Ashish Chaudhari', birthday: '31-01' },
        { name: 'Arjun Yogesh Kapadnis', birthday: '21-06' },
        { name: 'Maithili Dinesh Bramhankar', birthday: '14-05' },
        { name: 'Reyansh Tanmay Hiran', birthday: '14-06' },
        { name: 'Sanay Mukesh Harwani', birthday: '06-02' },
        { name: 'Aalap Atul Ahirrao', birthday: '31-12' },
        { name: 'Aayush Somnath Jejurkar', birthday: '02-03' },
        { name: 'Abhipray Agnihotri', birthday: '25-05' },
        { name: 'Advik Rohit Pagar', birthday: '20-02' },
        { name: 'Aikanshaa Sunit Mhasade', birthday: '30-12' },
        { name: 'Anjaneya Nayak', birthday: '04-09' },
        { name: 'Anura Gupta', birthday: '14-02' },
        { name: 'Arnav Shirish Malve', birthday: '28-04' },
        { name: 'Arya Prashant Patil', birthday: '08-08' },
        { name: 'Avanish Manoj Kale', birthday: '25-08' },
        { name: 'Avisha Harish Godse', birthday: '25-10' },
        { name: 'Lavanya Dhatrak', birthday: '25-01' },
        { name: 'Manas Rajendra Bagul', birthday: '15-10' },
        { name: 'Moulik Verma', birthday: '13-08' },
        { name: 'Rugveda Ravindra Chavan', birthday: '10-09' },
        { name: 'Rutul Pravin Pawar', birthday: '20-04' },
        { name: 'Saavi Yogesh Bhusare', birthday: '07-06' },
        { name: 'Samiksha Saklani', birthday: '22-11' },
        { name: 'Shaurya Abhay Malpure', birthday: '01-03' },
        { name: 'Shlok Alok Kumar', birthday: '26-08' },
        { name: 'Shloka Kumar', birthday: '03-10' },
        { name: 'Shubhra Sandeep Patil', birthday: '24-05' },
        { name: 'Swaroop Tushar Pagar', birthday: '13-08' },
        { name: 'Varad Kishor Gite', birthday: '05-03' },
        { name: 'Abhimanyu Atul Gosavi', birthday: '13-07' },
        { name: 'Abhinav Vasant Pathave', birthday: '17-10' },
        { name: 'Advika Amol Morankar', birthday: '13-02' },
        { name: 'Ananya Shrikant Kumavat', birthday: '17-02' },
        { name: 'Anwit Manoj Bhate', birthday: '10-12' },
        { name: 'Archit Atit Admulwar', birthday: '27-02' },
        { name: 'Asmi Amol Thakare', birthday: '26-10' },
        { name: 'Daksh Vishal Rane', birthday: '18-03' },
        { name: 'Dishita Lakhan Khatri', birthday: '10-11' },
        { name: 'Girija Vijay Kulkarni', birthday: '04-04' },
        { name: 'Ira Sameer Pathari', birthday: '07-11' },
        { name: 'Ira Sumant Biyani', birthday: '29-09' },
        { name: 'Isha Kumar', birthday: '03-10' },
        { name: 'Mitali Vikas Shirode', birthday: '15-10' },
        { name: 'Nairiti Vasant Khandvi', birthday: '23-10' },
        { name: 'Rahitya Akash Sachdev', birthday: '16-02' },
        { name: 'Riaan Mahesh Ahire', birthday: '15-06' },
        { name: 'Rudra Vikas Shewale', birthday: '18-04' },
        { name: 'Samarth Nandkumar Babar', birthday: '09-04' },
        { name: 'Sarvadnya Sudarshan Gite', birthday: '03-03' },
        { name: 'Shivaay Shrivastava', birthday: '27-08' },
        { name: 'Shravani Hemant Rayate', birthday: '28-07' },
        { name: 'Soham Girish Sulakshane', birthday: '28-10' },
        { name: 'Swaranshi Sagar Pagar', birthday: '11-10' },
        { name: 'Thanvi Sunil Jaiswal', birthday: '01-08' },
        { name: 'Varun Janardan Shelke', birthday: '19-07' },
        { name: 'Vihaan Vaibhav Pardeshi', birthday: '22-11' },
        { name: 'Vihan Pravin Kumbhar', birthday: '09-09' },
        { name: 'Vikrant Vijay Kulkarni', birthday: '04-04' },
        { name: 'Anaya Vishal Gaikwad', birthday: '20-09' },
        { name: 'Anirudh Kaushik', birthday: '20-03' },
        { name: 'Divyanka Sourabh Sharma', birthday: '06-10' },
        { name: 'Ishan Amit Kele', birthday: '23-07' },
        { name: 'Ivanna Kotak', birthday: '13-04' },
        { name: 'Jija Sameer Kale', birthday: '19-05' },
        { name: 'Khush Manish Tatiya', birthday: '22-12' },
        { name: 'Naitik Vardhaman Sancheti', birthday: '12-12' },
        { name: 'Riaansh Rahul Patil', birthday: '07-01' },
        { name: 'Riaansha Rahul Patil', birthday: '07-01' },
        { name: 'Shreeya Lalit Derle', birthday: '17-04' },
        { name: 'Vikram Balaji', birthday: '06-10' },
        { name: 'Yansh Abhijeet Tatiya', birthday: '09-03' },
        { name: 'Aaditya Sandip Rathod', birthday: '17-10' },
        { name: 'Aakanksh Sunit Kadam', birthday: '26-12' },
        { name: 'Aarush Nitin Patil', birthday: '28-05' },
        { name: 'Aashirya Saha', birthday: '23-05' },
        { name: 'Advik Abhiraj Pawar', birthday: '14-04' },
        { name: 'Alabhya Mishra', birthday: '17-01' },
        { name: 'Ananya Amol Pargaonkar', birthday: '11-08' },
        { name: 'Anisha Sharma', birthday: '24-05' },
        { name: 'Arnavi Narendra Khode', birthday: '05-06' },
        { name: 'Avanish Satish Vaishnav', birthday: '06-03' },
        { name: 'Devansh Sunil Thete', birthday: '18-11' },
        { name: 'Dwisha Digvijay Mandale', birthday: '17-09' },
        { name: 'Falak Sunil Jaiswal', birthday: '05-11' },
        { name: 'Hansika Pradeep Gangurde', birthday: '09-03' },
        { name: 'Jeenal Rahul Patil', birthday: '13-06' },
        { name: 'Jiyansh Pritesh Mutha', birthday: '23-06' },
        { name: 'Krita Siddharth Jain', birthday: '07-11' },
        { name: 'Mayank Rahul Kayastha', birthday: '14-03' },
        { name: 'Navya Nagariya', birthday: '16-06' },
        { name: 'Navya Swapnil Mahajan', birthday: '14-03' },
        { name: 'Niharika Kailas Bhoye', birthday: '09-09' },
        { name: 'Nitya Madhusudan More', birthday: '11-06' },
        { name: 'Ojas Sandeep Jadhav', birthday: '21-11' },
        { name: 'Ojaswi Anand Bodkhe', birthday: '02-08' },
        { name: 'Piyush Deepak Thakur', birthday: '09-04' },
        { name: 'Pranit Kiran Medhe', birthday: '07-03' },
        { name: 'Punit Harshad Patel', birthday: '01-10' },
        { name: 'Savreen Kaur Kohli', birthday: '08-06' },
        { name: 'Shaurya Lalit Bangera', birthday: '13-10' },
        { name: 'Subhansh Singh', birthday: '22-06' },
        { name: 'Swethan Tanmay Patel', birthday: '22-07' },
        { name: 'Tanish Balot', birthday: '11-11' },
        { name: 'Varuni Prashant Chavan', birthday: '16-08' },
        { name: 'Vivaan Nikhil Gavate', birthday: '24-05' },
        { name: 'Aaditya Yogesh Kadam', birthday: '13-11' },
        { name: 'Aarvi Amol Chandgude', birthday: '06-10' },
        { name: 'Aashna Rahul Mohite', birthday: '11-12' },
        { name: 'Abhinandan Gaurav Sonar', birthday: '07-10' },
        { name: 'Adamya Rai', birthday: '26-01' },
        { name: 'Advik Mahesh Salunke', birthday: '07-11' },
        { name: 'Anannya Yogesh Kolhe', birthday: '22-02' },
        { name: 'Aneya Bhushan Pingle', birthday: '19-03' },
        { name: 'Anvi Girish Bendkoli', birthday: '01-09' },
        { name: 'Aryan Mahendra Ahire', birthday: '07-12' },
        { name: 'Bhagwati Yogesh Jadhav', birthday: '05-11' },
        { name: 'Chinmayi Hemant Ner', birthday: '12-09' },
        { name: 'Divisha Singh', birthday: '15-07' },
        { name: 'Garv Satti', birthday: '21-05' },
        { name: 'Jatin Yogiraj Bhoye', birthday: '11-10' },
        { name: 'Kshitij Ashish Gogawale', birthday: '26-04' },
        { name: 'Manva Bhushan Ingale', birthday: '08-02' },
        { name: 'Nahush Nikhil Kulkarni', birthday: '20-10' },
        { name: 'Niket Pravin Padvi', birthday: '02-11' },
        { name: 'Nishna Samantaray', birthday: '10-04' },
        { name: 'Nyra Siddharth Rajgarhia', birthday: '20-11' },
        { name: 'Ojal Pritesh Bora', birthday: '09-01' },
        { name: 'Om Sachin Ilag', birthday: '28-06' },
        { name: 'Palvit Ravindra Gangurde', birthday: '25-03' },
        { name: 'Priyal Paresh Pawar', birthday: '24-08' },
        { name: 'Raghav Dhananjay Sangle', birthday: '04-06' },
        { name: 'Rajveer Hemant More', birthday: '22-04' },
        { name: 'Saanvi Rajendra Kadam', birthday: '05-03' },
        { name: 'Saumya Sunil Sangle', birthday: '06-01' },
        { name: 'Savani Sagar Khambait', birthday: '01-06' },
        { name: 'Sharvin Subhash Pawar', birthday: '26-11' },
        { name: 'Shilp Manjeet Raj', birthday: '17-09' },
        { name: 'Swarit Kartarsing Thakur', birthday: '06-10' },
        { name: 'Trisha Prashant Shimpi', birthday: '12-03' },
        { name: 'Vihaan Raju Aghav', birthday: '15-03' },
        { name: 'Aarvi Vijay Sonawane', birthday: '01-11' },
        { name: 'Aayansh Santosh Sonawane', birthday: '20-03' },
        { name: 'Advita Amol Deshmukh', birthday: '07-01' },
        { name: 'Advita Hemant Deshmukh', birthday: '17-04' },
        { name: 'Ameya Amit Kothawade', birthday: '01-06' },
        { name: 'Anaya Aniket Ambekar', birthday: '09-11' },
        { name: 'Anshuman Lalit Bhadange', birthday: '15-12' },
        { name: 'Anvi Yuvraj Vadaje', birthday: '16-11' },
        { name: 'Arihan Upadhyay', birthday: '19-10' },
        { name: 'Dhara Vilas Kuwar', birthday: '20-12' },
        { name: 'Dnyanada Sachin Kotwal', birthday: '28-03' },
        { name: 'Hridaya Yogesh Patil', birthday: '11-12' },
        { name: 'Jiyansh Mukesh Sunaria', birthday: '14-09' },
        { name: 'Kaira Aditya Karwa', birthday: '13-09' },
        { name: 'Kiyaan Parimal Sawant', birthday: '08-06' },
        { name: 'Kiyara Ajay Kapoor', birthday: '12-10' },
        { name: 'Mantra Pravin Sharma', birthday: '26-10' },
        { name: 'Mihan Mahavir Achaliya', birthday: '22-06' },
        { name: 'Nilay Piyush Kadam', birthday: '18-03' },
        { name: 'Nitya Devendra Solanki', birthday: '12-05' },
        { name: 'Omkar Umesh Jagzap', birthday: '20-07' },
        { name: 'Parth Aditya Ramdasi', birthday: '20-10' },
        { name: 'Prisha Swapnil Nikam', birthday: '21-09' },
        { name: 'Ridansh Harshal Patil', birthday: '01-01' },
        { name: 'Saanvi Shrivastava', birthday: '25-02' },
        { name: 'Samar Sagar Shelar', birthday: '26-05' },
        { name: 'Shaurya Vishal Saidpatil', birthday: '21-09' },
        { name: 'Shivansh Nitin Naik', birthday: '21-12' },
        { name: 'Shreyas Pravin Gite', birthday: '19-07' },
        { name: 'Tanvi Nitin Lute', birthday: '12-12' },
        { name: 'Vidyesh Deepak Bodke', birthday: '15-08' },
        { name: 'Viraj Jitendra Pawar', birthday: '06-12' },
        { name: 'Vivaan Sunny Parakh', birthday: '10-01' },
        { name: 'Vivan Sunil Bute', birthday: '10-07' },
        { name: 'Aabha Sujit Ugaonkar', birthday: '07-08' },
        { name: 'Aarohi Sunil Bandare', birthday: '23-06' },
        { name: 'Aarohi Vaibhav Bachhav', birthday: '12-11' },
        { name: 'Aaryan Jaywant Gite', birthday: '11-07' },
        { name: 'Aayansh Amol Patil', birthday: '27-05' },
        { name: 'Anaika Chetan Pagare', birthday: '03-11' },
        { name: 'Anika Sachin Mahale', birthday: '12-03' },
        { name: 'Anshuman Pathak', birthday: '19-09' },
        { name: 'Anvi Ashish Patil', birthday: '27-01' },
        { name: 'Arya Shashikant Jaiswal', birthday: '03-06' },
        { name: 'Anmay Singh', birthday: '25-10' },
        { name: 'Arav Samadhan Kshirsagar', birthday: '12-05' },
        { name: 'Arham Jain', birthday: '18-05' },
        { name: 'Avantika Gite', birthday: '28-10' },
        { name: 'Avishka Atul Bhanshi', birthday: '06-02' },
        { name: 'Dhairya Karan Shah', birthday: '14-08' },
        { name: 'Durvank Amol Supe', birthday: '15-01' },
        { name: 'Gaatha Bhushan Lunge', birthday: '02-01' },
        { name: 'Janhvi Jaywant Dhomase', birthday: '01-01' },
        { name: 'Malhar Vaibhav Borade', birthday: '18-01' },
        { name: 'Maurya Bhushan Deore', birthday: '27-10' },
        { name: 'Mehran Estyak Shaikh', birthday: '31-03' },
        { name: 'Nahush Prashant Aher', birthday: '01-03' },
        { name: 'Naitvik Sachin More', birthday: '18-06' },
        { name: 'Ovee Narendrakumar Chavan', birthday: '05-05' },
        { name: 'Rajveer Nitin Chavan', birthday: '13-09' },
        { name: 'Rudra Ghansham Hire', birthday: '15-11' },
        { name: 'Ruhi Manoj Tarachandani', birthday: '26-10' },
        { name: 'Saanvi Pradip Mairale', birthday: '12-07' },
        { name: 'Sanvi Sachin Pagar', birthday: '16-10' },
        { name: 'Shivraj Harshal Bhore', birthday: '11-10' },
        { name: 'Shravan Prashant Dhage', birthday: '18-01' },
        { name: 'Shrisha Shrikant Suryawanshi', birthday: '11-03' },
        { name: 'Swara Sandip Sonawane', birthday: '25-05' },
        { name: 'Swaraj Kishor Pawar', birthday: '09-04' },
        { name: 'Vansh Sandip Borase', birthday: '25-03' },
        { name: 'Veronika Jaiswal', birthday: '12-10' },
        { name: 'Vihaan Vishal Ochani', birthday: '13-07' },
        { name: 'Vihan Mukund Kshirsagar', birthday: '22-02' },
        { name: 'Yuvraj Yogesh Nagare', birthday: '14-11' },
        { name: 'Aadya Deven Gosavi', birthday: '28-12' },
        { name: 'Aara Sujit Ugaonkar', birthday: '07-08' },
        { name: 'Aarya Ajay Khamkar', birthday: '07-07' },
        { name: 'Agastya Harshad Jadhav', birthday: '05-04' },
        { name: 'Ananya Ravindra Jadhav', birthday: '19-05' },
        { name: 'Anay Kunal Dhurve', birthday: '25-04' },
        { name: 'Anjali Abhishek Jadhav', birthday: '24-06' },
        { name: 'Arnav Pradeep Bhor', birthday: '23-02' },
        { name: 'Arnav Vijay Arambhi', birthday: '07-03' },
        { name: 'Arush Ranjan', birthday: '31-01' },
        { name: 'Daksh Kumar', birthday: '09-03' },
        { name: 'Dhanvi Tandan', birthday: '25-05' },
        { name: 'Git Haresh Mandaviya', birthday: '04-04' },
        { name: 'Harman Abhijeet Mahana', birthday: '31-03' },
        { name: 'Jalaj Anand Chandak', birthday: '04-12' },
        { name: 'Laksh Diptesh Mutha', birthday: '29-09' },
        { name: 'Malhar Ranjit Ahire', birthday: '30-08' },
        { name: 'Manasvi Manoj More', birthday: '25-04' },
        { name: 'Mayank Raj', birthday: '03-07' },
        { name: 'Moksham Rupesh Chordiya', birthday: '08-07' },
        { name: 'Neil Vikram Sule', birthday: '15-07' },
        { name: 'Palak Vipul Shrishrimal', birthday: '19-04' },
        { name: 'Prajna Rani', birthday: '05-09' },
        { name: 'Rishwa Shailesh Patil', birthday: '25-06' },
        { name: 'Rudra Siddheshwar Ande', birthday: '22-12' },
        { name: 'Samaksha Gangrade', birthday: '19-07' },
        { name: 'Shlok Sachin Gaikwad', birthday: '03-05' },
        { name: 'Shreyas Varshney', birthday: '27-10' },
        { name: 'Shriraj Manoj Mhaske', birthday: '29-06' },
        { name: 'Snehit Amit Bhandari', birthday: '15-08' },
        { name: 'Swaraj Kapil Palekar', birthday: '31-03' },
        { name: 'Vihaan Sahebrao Gawale', birthday: '17-03' },
        { name: 'Yuvraj Hiraman Gangoda', birthday: '28-10' },
        { name: 'Aayansh Vishal Kakar', birthday: '30-03' },
        { name: 'Akshata Soni', birthday: '10-01' },
        { name: 'Aman Choudhary', birthday: '22-11' },
        { name: 'Amey Ajay Khairnar', birthday: '11-10' },
        { name: 'Ananya Anand Bakare', birthday: '19-09' },
        { name: 'Anay Sujit Sonje', birthday: '22-08' },
        { name: 'Anurag Sachin Gunjal', birthday: '14-10' },
        { name: 'Arya Abhijeet Patil', birthday: '10-07' },
        { name: 'Aryan Yadav', birthday: '27-11' },
        { name: 'Ayansh Mayur Chaudhari', birthday: '08-05' },
        { name: 'Bhargavi Nandlal Bahiram', birthday: '25-03' },
        { name: 'Heyansh Brijesh Patel', birthday: '16-10' },
        { name: 'Hiten Ketan Patil', birthday: '18-09' },
        { name: 'Ishani Satish Pardeshi', birthday: '20-04' },
        { name: 'Jaidev Vikram Gaikwad', birthday: '06-06' },
        { name: 'Labdhi Darshan Lunavat', birthday: '19-04' },
        { name: 'Meet Shashikant Sakhala', birthday: '22-06' },
        { name: 'Mrunmayee Sandesh Ghorpade', birthday: '08-01' },
        { name: 'Neel Sandeep Jagtap', birthday: '16-10' },
        { name: 'Parv Paresh Chordiya', birthday: '07-03' },
        { name: 'Pranika Nikhil Kulkarni', birthday: '31-08' },
        { name: 'Rudransh Ravindra Chavan', birthday: '17-09' },
        { name: 'Ruhi Amol Khairnar', birthday: '27-08' },
        { name: 'Sanskruti Jayesh Sonaje', birthday: '24-06' },
        { name: 'Shaurya Pankaj Palekar', birthday: '14-11' },
        { name: 'Shlok Sameer Kesarkar', birthday: '01-03' },
        { name: 'Shrisha Navnath Thube', birthday: '05-01' },
        { name: 'Shubhra Anant Zole', birthday: '29-07' },
        { name: 'Suhani Navdeep Ranjan', birthday: '24-12' },
        { name: 'Suryansh Chahal', birthday: '30-11' },
        { name: 'Swaraj Sachin Aher', birthday: '23-11' },
        { name: 'Viaan Gill', birthday: '29-10' },
        { name: 'Vihan Mitesh Jain', birthday: '22-04' },
        { name: 'Vihan Vilas Deshmukh', birthday: '24-10' },
        { name: 'Viraj Sudhir Mahajan', birthday: '29-06' },
        { name: 'Aadvik Swarnkar', birthday: '02-11' },
        { name: 'Aaradhya', birthday: '05-03' },
        { name: 'Aarush Sachin Walse', birthday: '23-07' },
        { name: 'Adhyayan Mahesh Badwe', birthday: '10-10' },
        { name: 'Anaisha Shailesh Khatwar', birthday: '08-03' },
        { name: 'Anish Shrikant Sonaje', birthday: '27-08' },
        { name: 'Anusha Vikram Phadol', birthday: '11-02' },
        { name: 'Anvay Kiran Kothule', birthday: '14-12' },
        { name: 'Chinmay Dinesh Patil', birthday: '05-08' },
        { name: 'Devarsh Kaustubh Pathak', birthday: '01-11' },
        { name: 'Dhrumit Amit Shah', birthday: '12-04' },
        { name: 'Hitansh Alai', birthday: '13-10' },
        { name: 'Ishwari Atmaram Sable', birthday: '28-10' },
        { name: 'Ishwari Rahul Hadpe', birthday: '24-03' },
        { name: 'Jay Prasad Gujar', birthday: '07-09' },
        { name: 'Kabir Sachdeva', birthday: '08-03' },
        { name: 'Mitansh Nikhil Parakh', birthday: '22-06' },
        { name: 'Myra Harshal Bedse', birthday: '23-06' },
        { name: 'Neelayan Adhikary', birthday: '22-01' },
        { name: 'Owi Ritesh Badhe', birthday: '25-03' },
        { name: 'Pratham Bhaskar Waghere', birthday: '27-07' },
        { name: 'Purvi Pankaj Bhalerao', birthday: '26-01' },
        { name: 'Rugvi Ranjit Gawande', birthday: '04-02' },
        { name: 'Saanvi Yogesh Aher', birthday: '15-02' },
        { name: 'Safal Sahil Patil', birthday: '11-04' },
        { name: 'Shaurya Umesh Tuppad', birthday: '15-12' },
        { name: 'Siddharth Pankaj Kokare', birthday: '04-05' },
        { name: 'Somya Hausare', birthday: '06-10' },
        { name: 'Sumukh Kiran Dokhale', birthday: '01-06' },
        { name: 'Swaraj Dattatray Deshmukh', birthday: '07-05' },
        { name: 'Swaroop Sachin Gambhire', birthday: '08-06' },
        { name: 'Tanmay Vishal Kasliwal', birthday: '20-10' },
        { name: 'Tirth Amit Purohit', birthday: '18-10' },
        { name: 'Vihaan Chandrakant Jagdhane', birthday: '25-03' },
        { name: 'Viren Vishal Gaikwad', birthday: '25-04' },
        { name: 'Vivaan Pritesh Bhatewara', birthday: '26-11' },
        { name: 'Aahrida Ankit Chitnavis', birthday: '01-08' },
        { name: 'Aarav Rahul Pagar', birthday: '17-09' },
        { name: 'Aarav Shripad Kulkarni', birthday: '23-10' },
        { name: 'Aayush Vikas Khambait', birthday: '01-05' },
        { name: 'Aditi Nilesh Baviskar', birthday: '08-10' },
        { name: 'Ajinkya Somnath Kotkar', birthday: '04-04' },
        { name: 'Anish Prashant Pawar', birthday: '13-10' },
        { name: 'Anvit Yadav', birthday: '02-01' },
        { name: 'Aradhya Anand Bakare', birthday: '13-09' },
        { name: 'Arjun Amol Jagzap', birthday: '22-11' },
        { name: 'Aum Hitesh Tilala', birthday: '04-12' },
        { name: 'Dhara Abhishek Nanavati', birthday: '13-02' },
        { name: 'Drushti Mukesh Patil', birthday: '22-02' },
        { name: 'Ibhan Pravin Pagare', birthday: '07-02' },
        { name: 'Jay Laxmikant Dinde', birthday: '13-04' },
        { name: 'Kahaan Jayesh Vora', birthday: '18-06' },
        { name: 'Kaushik Rajput', birthday: '06-09' },
        { name: 'Kriti Yadav', birthday: '19-12' },
        { name: 'Maanvi Vinay Bansod', birthday: '08-08' },
        { name: 'Moksh Umesh Pagar', birthday: '20-10' },
        { name: 'Namay Dinesh Deore', birthday: '22-11' },
        { name: 'Nitya Vikas Shewale', birthday: '28-07' },
        { name: 'Prithviraj Rajendra Warade', birthday: '10-05' },
        { name: 'Rajvardhan Sunil Khakale', birthday: '17-09' },
        { name: 'Reyansh Ranjan Kumar Ghosh', birthday: '17-11' },
        { name: 'Reyansh Satish Balte', birthday: '15-05' },
        { name: 'Shanaya Abhijeet Shinde', birthday: '18-06' },
        { name: 'Shivam Sharad Dhage', birthday: '21-04' },
        { name: 'Shreya Amol Dhatrak', birthday: '15-08' },
        { name: 'Shreyasi Bharat Ahire', birthday: '25-06' },
        { name: 'Soham Kishor Hujband', birthday: '17-01' },
        { name: 'Swanand Tushar Pagar', birthday: '22-03' },
        { name: 'Tejas Uday Devre', birthday: '09-05' },
        { name: 'Vaibhavi Sanjay Nagare', birthday: '07-12' },
        { name: 'Aaditya Chhagan Sali', birthday: '22-05' },
        { name: 'Aaradhya Amol Gite', birthday: '13-10' },
        { name: 'Aarya Sachin Patil', birthday: '18-03' },
        { name: 'Advaita Umesh Bairagi', birthday: '24-02' },
        { name: 'Amey Lakhoji Chaudhari', birthday: '17-05' },
        { name: 'Arnav Pradip Gore', birthday: '30-09' },
        { name: 'Arohi Sachin Falke', birthday: '29-05' },
        { name: 'Avnish Mayuresh Banekar', birthday: '12-11' },
        { name: 'Chitransh Tushar Lahoti', birthday: '12-06' },
        { name: 'Devansh Pratap', birthday: '18-02' },
        { name: 'Dhanvin Subhash Pawar', birthday: '19-10' },
        { name: 'Gaurang Monish Bhavsar', birthday: '05-10' },
        { name: 'Gauri Rahul Gahilod', birthday: '06-10' },
        { name: 'Ishaan Praveen Dimale', birthday: '05-08' },
        { name: 'Kairavi Himanshu Kulkarni', birthday: '08-01' },
        { name: 'Khushansh Devendra Sonawane', birthday: '06-09' },
        { name: 'Krishna Siddhanath Shinde', birthday: '29-10' },
        { name: 'Kritika Sachin Ilag', birthday: '10-11' },
        { name: 'Ovee Arun Khairnar', birthday: '30-06' },
        { name: 'Parth Yogesh Savadekar', birthday: '13-01' },
        { name: 'Riyansh Dhanraj Dhatrak', birthday: '22-08' },
        { name: 'Ruchira Vijay Khamat', birthday: '06-09' },
        { name: 'Rudra Nikhil Pagariya', birthday: '26-09' },
        { name: 'Sai Gokul Gite', birthday: '23-08' },
        { name: 'Sanchit Tushar Pawar', birthday: '23-01' },
        { name: 'Sarthak Prakash Bahiram', birthday: '27-11' },
        { name: 'Sharanya Lalit Derle', birthday: '31-03' },
        { name: 'Shivansh Meghraj Mate', birthday: '11-02' },
        { name: 'Shreyas Gopal Gaikwad', birthday: '01-03' },
        { name: 'Shruti Amol Dhatrak', birthday: '15-08' },
        { name: 'Spandan Yogesh Tadakhe', birthday: '23-10' },
        { name: 'Vaishnavi Dwivedi', birthday: '23-07' },
        { name: 'Vibha Piyush Lunawat', birthday: '19-05' },
        { name: 'Vidhi Sujit Jena', birthday: '26-03' },
        { name: 'Aaira Nitin Bashani', birthday: '16-08' },
        { name: 'Aakanksha Sudeep Bhambare', birthday: '18-01' },
        { name: 'Aditya Singh', birthday: '16-02' },
        { name: 'Advika Amit Deore', birthday: '04-01' },
        { name: 'Aradhya Vijay Tatiwar', birthday: '21-11' },
        { name: 'Arihant Abhishek Kasliwal', birthday: '23-06' },
        { name: 'Arnav Ashok Patil', birthday: '29-10' },
        { name: 'Arush Baranwal', birthday: '15-12' },
        { name: 'Bhuvi Goswami', birthday: '02-01' },
        { name: 'Dhairyasheel Vishal Pawar', birthday: '02-01' },
        { name: 'Durvesh Dinesh Dhatrak', birthday: '18-06' },
        { name: 'Gokul Dnyaneshwar Pawar', birthday: '11-12' },
        { name: 'Harsh Yogendra Rajput', birthday: '27-10' },
        { name: 'Harshvardhan Balaji Pingle', birthday: '28-09' },
        { name: 'Ishani Sanjay Chaudhari', birthday: '27-11' },
        { name: 'Jayesh Bhushan Chaudhari', birthday: '16-09' },
        { name: 'Jui Satish Wavhal', birthday: '17-09' },
        { name: 'Mayank Bhushan Patil', birthday: '08-05' },
        { name: 'Mayank Sanjay Bagul', birthday: '29-07' },
        { name: 'Nidhi Jaiswal', birthday: '11-09' },
        { name: 'Prajavan Amol Gangurde', birthday: '18-02' },
        { name: 'Prisha Ashwini Moolya', birthday: '29-08' },
        { name: 'Riya Mayur Modi', birthday: '30-08' },
        { name: 'Saee Sagar Jadhav', birthday: '31-05' },
        { name: 'Shashwat Sagar Dabhade', birthday: '14-04' },
        { name: 'Shaunak Samrat Pawar', birthday: '27-12' },
        { name: 'Shravani Sandeep Jadhav', birthday: '04-08' },
        { name: 'Soham Mukesh Pawar', birthday: '29-10' },
        { name: 'Spandan Yogesh Patil', birthday: '26-11' },
        { name: 'Swaranjali Sudam Dhatrak', birthday: '25-04' },
        { name: 'Tanishka Ramesh Surve', birthday: '21-05' },
        { name: 'Viraj Digambar Nirgude', birthday: '31-01' },
        { name: 'Viraj Kanaiya Maheshwari', birthday: '01-05' },
        { name: 'Viraj Navjyot Patil', birthday: '25-07' },
        { name: 'Viraj Vinay Patil', birthday: '23-11' },
        { name: 'Viren Ganesh Shelar', birthday: '02-02' },
        { name: 'Yashmi Guatam Nakrani', birthday: '02-09' },
        { name: 'Aaradhy Deepak Pagar', birthday: '30-07' },
        { name: 'Aaroh Ahirrao', birthday: '06-09' },
        { name: 'Aditi Deepak Patel', birthday: '21-02' },
        { name: 'Anurag Pankaj Borate', birthday: '14-03' },
        { name: 'Archit Amit Deshmukh', birthday: '10-11' },
        { name: 'Archit Mahendra Yeole', birthday: '04-01' },
        { name: 'Arohi Anil Mahale', birthday: '28-10' },
        { name: 'Atharv Pramod Jadhav', birthday: '12-09' },
        { name: 'Dhwani Chirag Malde', birthday: '08-08' },
        { name: 'Divyansh Nirmal', birthday: '10-03' },
        { name: 'Harsh Sachin Bodhale', birthday: '26-09' },
        { name: 'Ishan Umesh Salunkhe', birthday: '31-01' },
        { name: 'Jeevitha Sandrina', birthday: '18-08' },
        { name: 'Jeshvik Reddy Mothe', birthday: '06-09' },
        { name: 'Jui Nerkar', birthday: '02-05' },
        { name: 'Kavya Rakesh Bhoge', birthday: '10-02' },
        { name: 'Kimaya Sandeep Wable', birthday: '26-11' },
        { name: 'Mihika Gajanankumar Agrawal', birthday: '10-04' },
        { name: 'Milind Kumar Singh', birthday: '31-10' },
        { name: 'Mokshada Ravindra Kamodkar', birthday: '22-09' },
        { name: 'Nishka Abhijeet Mahana', birthday: '02-12' },
        { name: 'Nityanta Atulya', birthday: '27-03' },
        { name: 'Pratyush Shrikant Ahirrao', birthday: '08-12' },
        { name: 'Reva Prasad Chandratre', birthday: '21-02' },
        { name: 'Ronak Sharad Nagare', birthday: '24-02' },
        { name: 'Samruddhi Satish Suryawanshi', birthday: '13-04' },
        { name: 'Sarang Piyush Shinde', birthday: '12-02' },
        { name: 'Saumya Sumant Biyani', birthday: '24-05' },
        { name: 'Shreeraj Yogesh Deshmukh', birthday: '04-09' },
        { name: 'Swara Suryawanshi', birthday: '21-03' },
        { name: 'Tirth Ramchandra Shelar', birthday: '19-09' },
        { name: 'Urja Jaykumar Bhimani', birthday: '22-07' },
        { name: 'Vihaan Sumeet Lodh', birthday: '22-02' },
        { name: 'Vihaan Verma', birthday: '31-05' },
        { name: 'Vikrant Jagannath Tile', birthday: '13-12' },
        { name: 'Vrisan Jagdish Pawara', birthday: '07-03' },
        { name: 'Yash Jagdish Pekhale', birthday: '24-05' },
        { name: 'Aaditya Sharad Kale', birthday: '02-05' },
        { name: 'Aadya Tushar Shrivastav', birthday: '31-03' },
        { name: 'Aaradhya Vipul Khairnar', birthday: '14-09' },
        { name: 'Aarohee More', birthday: '21-01' },
        { name: 'Aarya Arjun Gavali', birthday: '19-08' },
        { name: 'Akshara Satishkumar Patil', birthday: '22-03' },
        { name: 'Anagh Sandeep Wakchaure', birthday: '15-07' },
        { name: 'Ananya Mayur Rajwade', birthday: '11-07' },
        { name: 'Ananya Sudeep Bhambare', birthday: '18-01' },
        { name: 'Ansh Vicky Agrawal', birthday: '21-07' },
        { name: 'Anshita Yogesh Thorat', birthday: '14-07' },
        { name: 'Arohi Kishor Pawar', birthday: '10-12' },
        { name: 'Ashwin Anaji Pawar', birthday: '22-06' },
        { name: 'Dhven Mahesh Dhadiwal', birthday: '08-08' },
        { name: 'Essa Suhas Ghuge', birthday: '13-10' },
        { name: 'Hansini Borade', birthday: '08-05' },
        { name: 'Harsh Amol Sakale', birthday: '07-01' },
        { name: 'Ilakshi Nitin Ahire', birthday: '21-05' },
        { name: 'Ira Sameer Farate', birthday: '10-09' },
        { name: 'Ishanya Dnyaneshwar Shitole', birthday: '14-05' },
        { name: 'Krisha Rupesh Parakh', birthday: '24-07' },
        { name: 'Manak Akhil Chatrath', birthday: '03-07' },
        { name: 'Mehpreet Kaur Kohli', birthday: '17-01' },
        { name: 'Mityaraj Sinh Parmar', birthday: '26-08' },
        { name: 'Mrunali Anil Nagare', birthday: '04-06' },
        { name: 'Naksh Mangesh Vispute', birthday: '22-06' },
        { name: 'Navya Rupesh Waykole', birthday: '27-08' },
        { name: 'Nitya Yadav', birthday: '24-09' },
        { name: 'Perva Aayush Bora', birthday: '06-09' },
        { name: 'Prarabdha Jadhav', birthday: '09-07' },
        { name: 'Saksham Sujit Jadhav', birthday: '25-02' },
        { name: 'Samartha Santosh Deokar', birthday: '03-10' },
        { name: 'Sanskruti Santosh Jamdhade', birthday: '04-12' },
        { name: 'Shriya Amol Pargaonkar', birthday: '14-03' },
        { name: 'Tanishq Sandeep Jadhav', birthday: '01-09' },
        { name: 'Tanmay Vilas Kumavat', birthday: '25-01' },
        { name: 'Varun Kumar', birthday: '29-11' },
        { name: 'Vedang Prashant More', birthday: '30-09' },
        { name: 'Aagatya Saurabh Parmar', birthday: '29-09' },
        { name: 'Aarav Atit Admulwar', birthday: '02-06' },
        { name: 'Aarna Atul Thakare', birthday: '29-10' },
        { name: 'Aastik Shah', birthday: '22-06' },
        { name: 'Advet Amit Kele', birthday: '29-09' },
        { name: 'Akshay Sachin Bhambere', birthday: '10-02' },
        { name: 'Ananya Sandeep Ishi', birthday: '01-07' },
        { name: 'Anmol Sharanabasappa Madiwalar', birthday: '03-06' },
        { name: 'Arnav Borgude', birthday: '12-12' },
        { name: 'Arnav Manish Mishra', birthday: '07-09' },
        { name: 'Ashutosh Anil Dhatrak', birthday: '05-08' },
        { name: 'Asmee Nilesh Bhavsar', birthday: '18-10' },
        { name: 'Ayu Ashiwin Alodariya', birthday: '13-05' },
        { name: 'Bhavika Sharma', birthday: '06-11' },
        { name: 'Dhyey Prakashbhai Hirpara', birthday: '12-07' },
        { name: 'Himank Bhavin Patel', birthday: '12-03' },
        { name: 'Ishaq Shaikh', birthday: '01-01' },
        { name: 'Krushna Bharat Gite', birthday: '07-06' },
        { name: 'Manyata Tushar Patil', birthday: '29-07' },
        { name: 'Neer Samirkumar Kaneriya', birthday: '31-12' },
        { name: 'Nishad Pavan Shirure', birthday: '09-07' },
        { name: 'Niyamat Kaur Brar', birthday: '19-12' },
        { name: 'Parth Santosh Jadhav', birthday: '08-09' },
        { name: 'Pratyusha Vijay Wagh', birthday: '25-12' },
        { name: 'Prince Kumar Saw', birthday: '16-06' },
        { name: 'Prithvij Amol Patil', birthday: '29-08' },
        { name: 'Purti Deepak Patel', birthday: '11-08' },
        { name: 'Rehansh Jain', birthday: '24-01' },
        { name: 'Rishika Rishidev Rai', birthday: '24-06' },
        { name: 'Shauri Suhas Chaudhari', birthday: '08-09' },
        { name: 'Shrvan Prashant Chavan', birthday: '01-05' },
        { name: 'Soumya Yadav', birthday: '16-11' },
        { name: 'Spandan Dinesh Desale', birthday: '15-07' },
        { name: 'Spruha Dinesh Desale', birthday: '15-07' },
        { name: 'Swadhyay Himanshu Saklani', birthday: '24-05' },
        { name: 'Swanand Pushkaraj Akolkar', birthday: '02-02' },
        { name: 'Trisha Gaikwad', birthday: '03-05' },
        { name: 'Vashnawi .', birthday: '07-01' },
        { name: 'Aarav Jitendra Singh', birthday: '17-09' },
        { name: 'Aarna Aditya Karwa', birthday: '25-09' },
        { name: 'Aarush Jitendra Patil', birthday: '19-10' },
        { name: 'Aarya Gopal Mhasde', birthday: '13-10' },
        { name: 'Agrim Yadav', birthday: '11-10' },
        { name: 'Akshant Ashish Khode', birthday: '09-05' },
        { name: 'Akshant Prashant Ufade', birthday: '11-09' },
        { name: 'Akshita Bhanupratap Sharma', birthday: '15-10' },
        { name: 'Ananya Shrikant Bhadange', birthday: '24-08' },
        { name: 'Anurag Amol Pawar', birthday: '30-04' },
        { name: 'Arush Bhingare', birthday: '10-08' },
        { name: 'Aryan Prashant Bhamare', birthday: '26-09' },
        { name: 'Asmi Punase', birthday: '18-04' },
        { name: 'Avishi Vivek Singh', birthday: '11-11' },
        { name: 'Garv Naranbhai Patel', birthday: '06-01' },
        { name: 'Harsh Rajendra Bagul', birthday: '17-01' },
        { name: 'Harsha Joharapuram Pothula', birthday: '22-11' },
        { name: 'Ishani Paras Yadav', birthday: '19-05' },
        { name: 'Kavya Deepak Bhambere', birthday: '11-09' },
        { name: 'Manthan Chandrashekar Babhare', birthday: '13-02' },
        { name: 'Nirbhik Sharma', birthday: '26-09' },
        { name: 'Ojas Mohan Kulkarni', birthday: '05-09' },
        { name: 'Pranamya Mahesh Ahire', birthday: '15-04' },
        { name: 'Purvi Siyaram Sharma', birthday: '07-09' },
        { name: 'Pushkar Digamber Singh', birthday: '01-08' },
        { name: 'Pushkarini Hemant Ner', birthday: '13-11' },
        { name: 'Rewa Abhishek Kurdukar', birthday: '02-09' },
        { name: 'Ridhaan Vardhaman Sancheti', birthday: '05-08' },
        { name: 'Shaurya Kshitij Patil', birthday: '01-06' },
        { name: 'Shivraj Vinayak Khaire', birthday: '30-04' },
        { name: 'Shree Sajaykumar Patil', birthday: '01-10' },
        { name: 'Shubhra Nitin Gajare', birthday: '15-08' },
        { name: 'Siddhant Bhushan Lalwani', birthday: '01-02' },
        { name: 'Vaishnavi Singh', birthday: '13-10' },
        { name: 'Vamika Sharma', birthday: '11-10' },
        { name: 'Viraj Kamlesh Singh', birthday: '28-01' },
        { name: 'Vivan Vishal Bhagwat', birthday: '19-10' },
        { name: 'Aabha Nandkishor Raundal', birthday: '31-03' },
        { name: 'Aadhya Meena', birthday: '16-09' },
        { name: 'Aagam Pritish Bhandari', birthday: '23-04' },
        { name: 'Aayansh Anupam Gupta', birthday: '19-01' },
        { name: 'Aditi Avinash Shisode', birthday: '20-04' },
        { name: 'Ananya Ganesh More', birthday: '21-09' },
        { name: 'Arnav Amol Morankar', birthday: '30-05' },
        { name: 'Arnav Sunil Dalvi', birthday: '24-01' },
        { name: 'Arnav Sunit Thorat', birthday: '21-09' },
        { name: 'Dhwaj Piyush Bora', birthday: '06-03' },
        { name: 'Divyansh Nehra', birthday: '22-12' },
        { name: 'Diya Deepesh Bhandari', birthday: '28-07' },
        { name: 'I Pradnya', birthday: '20-05' },
        { name: 'Kshitij Abhishek Panwar', birthday: '06-03' },
        { name: 'Manas Manoj Rayate', birthday: '09-08' },
        { name: 'Myra Amit Basak', birthday: '23-08' },
        { name: 'Nakul Walia', birthday: '27-04' },
        { name: 'Naman Sachin Vidhate', birthday: '24-04' },
        { name: 'Nikita Anupam Singh', birthday: '07-05' },
        { name: 'Pragya Jha', birthday: '19-05' },
        { name: 'Rajveer Sham Mullani', birthday: '02-02' },
        { name: 'Rudhav Vishal Gaikwad', birthday: '25-08' },
        { name: 'Saachi Umesh Bhosale', birthday: '09-07' },
        { name: 'Sanika Sachin Borkar', birthday: '04-01' },
        { name: 'Sharwaree Surendra Billade', birthday: '20-02' },
        { name: 'Shloka Mahesh Sonkul', birthday: '27-12' },
        { name: 'Shubhra Sameer Pathari', birthday: '24-08' },
        { name: 'Soumya Pawan Kumar Tandekar', birthday: '03-09' },
        { name: 'Sparsh Sandip Sudke', birthday: '29-12' },
        { name: 'Swaanik Digvijay Mandale', birthday: '17-06' },
        { name: 'Swaraj Amar Nikam', birthday: '05-04' },
        { name: 'Vedant Abhishek Sonwane', birthday: '31-12' },
        { name: 'Aaditee Pankaj Kokare', birthday: '08-09' },
        { name: 'Aarav Abhijeet Padalkar', birthday: '25-01' },
        { name: 'Adhrit Amol Konde', birthday: '09-01' },
        { name: 'Advika Bharati', birthday: '25-11' },
        { name: 'Anishaa Naskar', birthday: '17-01' },
        { name: 'Anvesh Navendu Kumar', birthday: '07-11' },
        { name: 'Anvi Amit Nathe', birthday: '24-03' },
        { name: 'Anvi Kunal Dhurve', birthday: '27-08' },
        { name: 'Arnav Naresh Bharule', birthday: '22-09' },
        { name: 'Arnav Ravindra Gaware', birthday: '24-08' },
        { name: 'Arnav Sham Pagar', birthday: '19-02' },
        { name: 'Arsh Mohammed Sufiyan Shaikh', birthday: '15-08' },
        { name: 'Aryan Ujwal Ingale', birthday: '27-02' },
        { name: 'Bhargav Sachin Kapadnis', birthday: '22-10' },
        { name: 'Charvi Talikot', birthday: '10-04' }
    ];

    

    
     checkBirthdays(birthdays);
});

function checkBirthdays(data) {
    const today = new Date();
    const dd = String(today.getDate()).padStart(2, '0');
    const mm = String(today.getMonth() + 1).padStart(2, '0'); // January is 0!
    const todayFormatted = dd + '-' + mm;

    let birthdayListHTML = '';

    const matchingBirthdays = data.filter(person => person.birthday === todayFormatted);

    if (matchingBirthdays.length === 1) {
        const person = matchingBirthdays[0];
        birthdayListHTML = `
            <div class="birthday">
                <p><span class="name">${person.name}</span> is celebrating their birthday today! 🎉🎂</p>
            </div>
        `;
    } else if (matchingBirthdays.length > 1) {
        birthdayListHTML = '<div class="birthday"><p>They are celebrating their birthdays today!</p>';
        matchingBirthdays.forEach(person => {
            birthdayListHTML += `<p><span class="name">${person.name} 🎉🎂</span>  </p>`;
        });
        birthdayListHTML += '</div>';
    } else {
        birthdayListHTML = '<p>No birthdays today!</p>';
    }

    document.getElementById('birthdayList').innerHTML = birthdayListHTML;
}





     
   
